<a href="https://colab.research.google.com/github/anselmo-pitombeira/Notebooks/blob/master/Simple_NN_in_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Implementation of a simple neural network in Numpy

In [34]:
import autograd.numpy as np
import pandas as pd
from autograd import grad


In [11]:
##Read data
dados = pd.read_csv("housing.csv",  header=None, delim_whitespace=True)
dados.columns = ['CRIM','ZN','INDUS','CHAS','NOX','RM','AGE','DIS','RAD','TAX','PTRATIO','B', 'LSTAT','MEDV']
dados2 = dados[["CRIM","INDUS","NOX","AGE","TAX"]]

In [37]:
##Define activation function (RELu)
def relu(x):

  """
  A rectifier linear unit activation function.
  """

  output = np.copy(x)
  output[output<0] = 0

  return output


##Define forward computation
def forward_pass(x,W1,W2,b1,b2):

  """
  Forward computation of neural network.
  """
  
  ##Compute hidden layer
  h = relu(W1.dot(x)+b1)

  ##Compute output layer (just a linear function)
  y = W2.dot(h)+b2
  y = y.reshape(-1,1)

  return y

def loss_function(obs_y, pred_y):

  """
  Average quadratic loss
  """

  N = obs_y.size

  loss = 1/N*np.sum((obs_y-pred_y)**2)

  return loss

##Size of input vector
n = dados2.shape[1]

##Desired number of neurons on hidden layer
m = 10

##Weight matrix of hidden layer (initialized as random)
W1 = np.random.uniform(-1,1,(m,n))
print("W1 = ", W1)

##Bias vector of hidden layer
b1 = np.random.uniform(-1,1,(m,1))

##Weight matrix of output layer (output is univariate)
W2 = np.random.uniform(-1,1,(1,m))
print("\nW2 = ", W2)

##Bias scalar of output layer
b2 = np.random.uniform(-1,1)


X = dados2.values.transpose()
print("X shape = ", X.shape)

y_obs = dados["MEDV"].values.reshape(-1,1)

##Forward pass
y_pred = forward_pass(X,W1,W2,b1,b2)

##Compute loss

loss = loss_function(y_pred,y_obs)

loss_grad = grad(loss_function)

print("Loss Grad shape = ", loss_grad(y_pred,y_obs).shape)


W1 =  [[ 0.310581   -0.68158347  0.41885685 -0.63987983 -0.92482791]
 [-0.34182128 -0.98773225 -0.04399259  0.84784888  0.40796912]
 [ 0.3849309   0.20957798 -0.5264861   0.83090452 -0.46488442]
 [-0.11758699 -0.70726251  0.84435375  0.55855202  0.08632298]
 [ 0.55987148 -0.94767378  0.76353469  0.53034073  0.53516492]
 [ 0.70549295 -0.81475155  0.70519321  0.56921146 -0.78906753]
 [ 0.12200465  0.8559842  -0.18857738  0.40782298  0.69776514]
 [ 0.24422107  0.21043034  0.34295125  0.56944705 -0.57867163]
 [ 0.77909649 -0.35047273 -0.48260386 -0.12865198  0.22870869]
 [-0.57775098 -0.68536643 -0.25320226  0.32158062 -0.5807368 ]]

W2 =  [[-0.67065669  0.91475886 -0.93029911  0.54073808  0.48532503 -0.4218625
  -0.54190818  0.78270808  0.80665493  0.82480373]]
X shape =  (5, 506)
Loss Grad shape =  (506, 1)
