# **Introdução ao NumPy**

Autor: Prof. Dr. Anselmo R. Pitombeira Neto,
OPL - Pesquisa Operacional em Produção e Logística,
Departamento de Engenharia de Produção,
Universidade Federal do Ceará

ver 0.1

---

O Numerical Python (NumPy) é uma biblioteca para a linguagem Python com funções para se trabalhar com computação numérica. Seu principal objeto é o vetor n-dimensional, ou `ndarray`. Um vetor n-dimensional também é conhecido pelo nome *tensor*. A principal característica do `ndarray` é que ele deve ser homogêneo, ou seja, diferentemente do objeto lista, todos os seus elementos devem ser do mesmo tipo.

## Criação de tensores

Pode-se criar um `ndarray` passando um container como inicializador para um objeto da classe `array`:

In [1]:
import numpy as np
v = np.array([1,2,3,4])
print(v)

[1 2 3 4]


O tipo dos elementos de um `ndarray` pode ser acessado por meio do atributo `dtype`

In [2]:
print(v.dtype)

int64


Neste caso, ao criar o vetor, o tipo *default* assumido foi `int64`, mas o tipo desejado pode ser especificado na criação do tensor:

In [3]:
v = np.array([1,2,3,4], dtype='float64')
print(v.dtype)

float64


No caso, se utilizarmos números com pontos decimais, o tipo será automaticamente `float`:

In [4]:
v = np.array([1.0,2.0,3.0,4.0])
print(v.dtype)

float64


Os tensores NumPy também possuem um atributo chamado `shape`. Esse atributo indica a forma do tensor, por exemplo:

In [5]:
print(v.shape)

(4,)


Neste caso, o tensor `v` possui 1 dimensão (ou eixo) com 4 elementos. Um tensor unidimensional corresponde a um vetor. Podemos também criar um tensor bidimensional (uma matriz) usando o atributo `shape`:


In [6]:
v = np.array([1,2,3,4])
v.shape = (2,2)
print(v)

[[1 2]
 [3 4]]


Outra forma útil de mudar o shape de um tensor é simplesmente utilizando a função reshape:

In [7]:
v = np.array([1,2,3,4]).reshape(2,2)
print(v)

[[1 2]
 [3 4]]


O número de eixos (ou dimensões) de um tensor é dado pelo atributo `ndim`, enquanto o número total de elementos é dado por `size`:

In [8]:
v = np.array(range(50)).reshape(2,5,5)

print('Shape = ', v.shape)
print('Número de dimensões = ', v.ndim)
print('Número de elementos = ', v.size)
print('Tensor v = \n', v)

Shape =  (2, 5, 5)
Número de dimensões =  3
Número de elementos =  50
Tensor v = 
 [[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]
  [20 21 22 23 24]]

 [[25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]
  [40 41 42 43 44]
  [45 46 47 48 49]]]


As funções `zeros`, `ones` e `diag` são muito convenientes para a criação de tensores:

In [9]:
V = np.zeros((3,3))
print('V = \n', V)
U = np.ones((3,3))
print('U = \n', U)
D = np.diag([10, 10, 10])
print('D = \n', D)

V = 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
U = 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
D = 
 [[10  0  0]
 [ 0 10  0]
 [ 0  0 10]]


As funções arange e linspace permitem a criação de sequências como tensores NumPy:

In [10]:
v = np.arange(0, 5, 0.5)
u = np.linspace(0, 5, 10)
print("v =", v)
print("u =", u)

v = [0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
u = [0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


## Indexação de tensores

O acesso aos elementos de um tensor pode ser feito utilizando colchetes e o índice do elemento:

In [11]:
print(v[1])

0.5


In [12]:
Tensores com rank maior ou igual a 2, por exemplo, acessar o elemento com índice 0 no primeiro eixo e índice 1 no segundo eixo:

SyntaxError: ignored

In [0]:
v = np.array([10, 20, 30, 40]).reshape(2,2)
print(v[0,1])

Tensor de rank 3:

In [0]:
v = np.arange(8).reshape(2,2,2)
print("v =\n", v)
print("\n v[0,0,1] =", v[0,0,1])

Subtensores contíguos de um tensor podem ser acessados utilizando o operador " : ". Note que neste caso o NumPy não faz uma cópia dos dados, mas apenas cria uma *view* dos dados:

In [0]:
v = np.arange(10)
u = v[1:3]
print(u)

No caso de uma matriz (um tensor de rank 2), pode-se acessar submatrizes:

In [0]:
A = np.arange(15).reshape(3,5)
print(A)

Vamos selecionar somente a submatriz correspondente às linhas 0 e 1, e colunas 2 e 3:

In [0]:
subA = A[0:2, 2:4]
print(subA)

A indexação pode ser realiza também passando uma lista ou outro tensor que contém os índices dos elementos que queremos selecionar, por exemplo, abaixo queremos selecionar somente os elementos com índice 2 e 3. Observe que, neste caso, o tensor v resultante é um novo objeto criado a partir do tensor u e alocado na memória. Ocorre cópia dos dados.

---



In [0]:
u = np.array([2.0, 3.5, 4.0, -10.1])
v = u[[2,3]]
print(v)

Filtrando as colunas 2 e 4 de uma matriz:

In [0]:
A = np.arange(10).reshape(2,5)
B = A[:, [2,4]]
print("A =\n", A)
print("B =\n", B)

## Operações sobre tensores


---



As operações sobre tensores NumPy são realizada elemento a elemento, por exemplo:

In [0]:
v = np.array([10,20,30])
u = np.array([2,2,2])
w = u+v
print(w)

Note que no caso dos operadores * e / a operação também ocorre elemento a elemento:

In [0]:
w = u*v
print("w =", w)
x = u/v
print("x =", x)

Elevar todos os elementos de um vetor a uma potência:

In [0]:
x = np.array([10, 20])
y = x**2
print(y)

Alguns operadores unários como a média, menor valor, maior valor, etc possuem funções específicas:

In [0]:
x = np.arange(10)
media = x.mean()
menor_valor = np.min(x)
arg_max = np.argmax(x)
print("Média =", media)
print("Menor valor =", menor_valor)
print("Arg max =", arg_max)

Em tensores com rank maior ou igual a 2 pode-se identifcar o eixo em que se deseja aplicar as funções min, max, etc. Caso o eixo não seja especificado, a funções retornará o menor/maior valor entre todos incluindo todos os eixos:

In [0]:
A = np.array([10, 30, 40, 20]).reshape(2,2)
menor= A.min()
menor_colunas = A.min(axis=0)
print("A = \n", A)
print("Menor valor = ", menor)
print("Menor valor em cada coluna =", menor_colunas)

A operação de produto interno (ou produto escalar) pode ser realizada pela função `dot`:

In [0]:
w = np.dot(u, v)
print("w =", w)

x = u.dot(v)
print("x =", x)

Multiplicação de um escalar por um vetor:

In [0]:
print("w =", w)
x = 10*w
print("x =", x)

Um erro muito comum no uso do NumPy é não explorar sua eficiência computacional por meio das operações vetoriais. Dentro do possível, deve-se sempre organizar implementação de um algoritmo utilizando somente operações sobre tensores. Por exemplo, abaixo é feita a comparação entre o tempo computacional em usar a operação `dot` e uma implementação da mesma operação utilizando loops:

In [0]:
def produto_interno(u, v):
  
  prod = 0
  
  for i in range(u.size):
    prod+=u[i]*v[i]
    
  return prod

u = np.random.rand(10000)
v = np.random.rand(10000)

%timeit produto_interno(u,v)
%timeit np.dot(u,v)

Observe que a operação `dot` é muito mais rápida. Isso ocorre porque a operação `dot` é implementada em linguagem C e realiza a operação de maneira vetorizada.

## Matrizes

Em NumPy, matrizes são tensores com 2 dimensões (tensores de rank 2). Embora exista um objeto `matrix`, em geral é mais prático tratar matrizes como tensores de rank 2:

In [0]:
A = np.array([[10, 20], [30, 40]])
print(A)

In [0]:
Criar uma matriz identidade:

In [0]:
I = np.eye(5)
print(I)

Matrizes diagonais:

In [0]:
D = np.diag(np.arange(5))
print(D)

## Operações sobre matrizes

Multilplicação de vetores e matrizes é realizada por meio da função `dot`:

In [0]:
v = np.array([10, 10])
A = np.arange(4).reshape(2,2)
u = A.dot(v)
print(u)

Multiplicação de matrizes:

In [0]:
A = np.ones((2,2))
B = 10*np.ones((2,2))
C= np.dot(A,B)
print(C)

A multiplicação de matrizes também pode ser realizada por meio do operador @:

In [0]:
C = A @ B
print(C)

Transposição de matrizes pode ser feita com a função `transpose` ou simplesmente com a letra " `T` ":

In [0]:
A = np.arange(4).reshape(2,2)
print("Transposta de A =\n", A.transpose())
print("Transposta de A =\n", A.T)

## Funções universais

O NumPy oferece diversas funções matemáticas clássicas, como exponencial, logaritmo, etc. Essas funções são aplicadas a todos os elementos de um tensor. Exemplo de aplicação da função exponencial:

In [0]:
u = np.arange(5)
v = np.exp(u)
print(v)

Função seno:

In [0]:
v = np.sin(u)
print(v)

##Operadores lógicos

As operações lógicas entre tensores ocorrem elemento a elemento. O resultado da operação é um tensor booleano com valores `True` ou `False` que indicam se a condição lógica é verdadeira ou falsa:

In [0]:
u = np.arange(4).reshape(2,2)
v = 2*np.ones((2,2))
w = u > v
print(w)

Os tensores booleanos podem ser usados para filtrar valores em um tensor, por exemplo:

In [0]:
u = np.array([-1, 2, -3])
v = np.array([True, False, True])
print(u[v])

Note que podemos obter o mesmo efeito anterior de filtrar somente os valores negativos fazendo:

In [0]:
w = u[u < 0]
print(w)

E podemos também atribuir um valor específico aos elementos de um tensor que satisfazem uma certa condições, por exemplo zerar todos os valores negativos:

In [0]:
print("u =", u)
u[u < 0] = 0
print("u =", u)


---

# Geração de números aleatórios

---

# Álgebra Linear

O NumPy possui um submódulo específico para a realização de operações típicas da álgebra linear chamado `linalg`. Com este módulo é possível resolver sistemas lineares, obter inversas de matrizes, calcular autovalores e autovetores, etc.

## Solução de sistemas lineares

A solução de sistemas de equações lineares do tipo $Ax = b$ pode ser realizada por meio da função `solve`:

In [0]:
A = np.array([10, 20, 30, 40]).reshape(2,2)
b = np.array([5,10])
x = np.linalg.solve(A, b)
print(x)

Caso $b =[b_1, b_2, ..., b_p]$ em que cada $b_j, j = 1, ..., p$ é um vetor coluna, a função `solve` retorna uma matriz $x = [x_1, x_2, ..., x_p]$ em que cada $x_j$  é solução do sistema linear $Ax_j = b_j$.

In [0]:
b1 = np.array([5, 10]).reshape(2,1)
b2 = np.array([10, 12]).reshape(2,1)
b = np.hstack([b1, b2])
print("b =\n", b)
x = np.linalg.solve(A, b)
print("x =\n", x)